### ISSUE TITLE
Missing kickstart file for almalinux-8-init

### ISSUE THREAD

**Issue by tcassaert** [srbala/kickstart2rootfs#10]
I was trying the steps for the `init` Docker files, but the kickstart file seems to be missing to be able to complete those steps.
I first built the Docker image, that went perfectly fine. But the next step failed:

```
podman run --rm --privileged -v "$PWD:/build:z" \
    -e KICKSTART_FILE=kickstarts/almalinux-8-init.x86_64.ks \
    -e IMAGE_NAME=almalinux-8-docker-init.x86_64.tar.gz \
    -e OUTPUT_DIR=init \
    -e BUILD_TYPE=init \
    almalinux/ks2rootfs
Build output files will be in './result_x86_64' folder ...
Output directory ./result_x86_64 created successfully

ks2rootfs - Script input summary:

FLAGS
-----
FLAG_OUTOUT_PWD : false
FLAG_WRITE_META : false
FLAG_RETAIN_LOG : false

VARIABLES
---------
BUILD_WORK_DIR  : ./
OUTPUT_DIR      : ./result_x86_64
BUILD_LOGDIR    : ./result_x86_64/logs
INPUT_KICKSTART : ./kickstarts/almalinux-8-init.x86_64.ks
OUTPUT_ROOTFS   : ./result_x86_64/almalinux-8-docker-init.x86_64.tar.gz
BUILD_COMPTYPE  : xz
BUILD_TYPE      : init
2022-02-09 14:57:53,298: livemedia-creator v28.14.62-1
2022-02-09 14:57:53,299: selinux is Disabled
2022-02-09 14:57:53,300: kickstart file (/build/kickstarts/almalinux-8-init.x86_64.ks) is missing.
```

**Comment by srbala** [comment]
@tcassaert I think, we need an update to documentation. Original kickstart scripts are in `docker-images` repo. Please try these steps below.

```sh
git clone --depth=1 https://github.com/AlmaLinux/docker-images.git
cd docker-images
podman run --rm --privileged -v "$PWD:/build:z" \
    -e KICKSTART_FILE=kickstarts/almalinux-8-init.ks \
    -e IMAGE_NAME=almalinux-8-docker-init.x86_64.tar.gz \
    -e OUTPUT_DIR=init \
    -e BUILD_TYPE=init \
    almalinux/ks2rootfs
```

**Comment by tcassaert** [comment]
@srbala Thanks a lot for that pointer! 
The only thing that I needed to adapt was the kickstart file name itself. In that repo, it's without the `x86_64` in its name.

Should I try to make the documentation more clear?

**Comment by srbala** [comment]
@tcassaert good point. When we started we had separate kickstart files for each arch, over the time we merged them together. We will be glad to accept a PR.

**Comment by tcassaert** [comment]
I've created a PR at the `docker-images` repo.
Was not entirely sure what should be the good approach to document this repo.

**Comment by srbala** [comment]
`docker-images` PR merged
